version: '3'
services:

  postgres:
    image: postgres:11.6
    restart: "on-failure"
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      PGDATA: "/var/lib/postgres"
    ports:
      - '5432:5432'
    expose:
      - '5432'        
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgres    
  